### ISSUE TITLE
Erreur: ENOENT (No such file or directory) /storage/emulated/0/Documents/Attestations

### ISSUE THREAD

**Issue by stuart12** [AdrienPoupa/AttestationDeplacement#9]
merci pour [Attestation Coronavirus](https://f-droid.org/en/packages/com.adrienpoupa.attestationcoronavirus/).  J'ai [LineageOS 17.1](https://download.lineageos.org/enchilada) (Android 10) et la version 0.0.4

J'ai rempli toutes les champs, je clique sur "GÉNÉRER" et j'ai toast qui dit "Erreur".  Adb logcat me dit:

```
04-06 22:56:11.208  1010  1540 E LightsService: Light requested not available on this device. 2
04-06 22:56:11.296 29260 29260 W System.err: java.io.FileNotFoundException: /storage/emulated/0/Documents/Attestations/Attestation-2020-04-06-22-56.pdf: open failed: ENOENT (No such file or directory)
04-06 22:56:11.296 29260 29260 W System.err: 	at libcore.io.IoBridge.open(IoBridge.java:496)
04-06 22:56:11.296 29260 29260 W System.err: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
04-06 22:56:11.296 29260 29260 W System.err: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
04-06 22:56:11.296 29260 29260 W System.err: 	at com.itextpdf.io.util.FileUtil.getBufferedOutputStream(FileUtil.java:161)
04-06 22:56:11.296 29260 29260 W System.err: 	at com.itextpdf.kernel.pdf.PdfWriter.<init>(PdfWriter.java:143)
04-06 22:56:11.296 29260 29260 W System.err: 	at com.itextpdf.kernel.pdf.PdfWriter.<init>(PdfWriter.java:132)
04-06 22:56:11.296 29260 29260 W System.err: 	at com.itextpdf.kernel.pdf.PdfWriter.<init>(PdfWriter.java:105)
04-06 22:56:11.297 29260 29260 W System.err: 	at com.adrienpoupa.attestationcoronavirus.CreateAttestationActivity.generate(CreateAttestationActivity.java:150)
04-06 22:56:11.297 29260 29260 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-06 22:56:11.297 29260 29260 W System.err: 	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:397)
04-06 22:56:11.297 29260 29260 W System.err: 	at android.view.View.performClick(View.java:7259)
04-06 22:56:11.297 29260 29260 W System.err: 	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:967)
04-06 22:56:11.297 29260 29260 W System.err: 	at android.view.View.performClickInternal(View.java:7236)
04-06 22:56:11.297 29260 29260 W System.err: 	at android.view.View.access$3600(View.java:801)
04-06 22:56:11.297 29260 29260 W System.err: 	at android.view.View$PerformClick.run(View.java:27892)
04-06 22:56:11.297 29260 29260 W System.err: 	at android.os.Handler.handleCallback(Handler.java:883)
04-06 22:56:11.297 29260 29260 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-06 22:56:11.297 29260 29260 W System.err: 	at android.os.Looper.loop(Looper.java:214)
04-06 22:56:11.297 29260 29260 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
04-06 22:56:11.297 29260 29260 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-06 22:56:11.297 29260 29260 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
04-06 22:56:11.297 29260 29260 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
04-06 22:56:11.297 29260 29260 W System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
04-06 22:56:11.297 29260 29260 W System.err: 	at libcore.io.Linux.open(Native Method)
04-06 22:56:11.297 29260 29260 W System.err: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
04-06 22:56:11.297 29260 29260 W System.err: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
04-06 22:56:11.297 29260 29260 W System.err: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
04-06 22:56:11.297 29260 29260 W System.err: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
04-06 22:56:11.297 29260 29260 W System.err: 	at libcore.io.IoBridge.open(IoBridge.java:482)
04-06 22:56:11.297 29260 29260 W System.err: 	... 21 more
```

J'ai utilisé mon [navigateur de fichiers](https://f-droid.org/en/packages/com.simplemobiletools.filemanager.pro/) pour créer `/storage/emulated/0/Documents/Attestations` et maintenant j'ai  `EACCES (Permission denied)`:

```
04-06 23:00:18.437  1010  1540 E LightsService: Light requested not available on this device. 2
04-06 23:00:18.514 29260 29260 W System.err: java.io.FileNotFoundException: /storage/emulated/0/Documents/Attestations/Attestation-2020-04-06-23-00.pdf: open failed: EACCES (Permission denied)
04-06 23:00:18.514 29260 29260 W System.err: 	at libcore.io.IoBridge.open(IoBridge.java:496)
04-06 23:00:18.514 29260 29260 W System.err: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
04-06 23:00:18.514 29260 29260 W System.err: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
04-06 23:00:18.514 29260 29260 W System.err: 	at com.itextpdf.io.util.FileUtil.getBufferedOutputStream(FileUtil.java:161)
04-06 23:00:18.514 29260 29260 W System.err: 	at com.itextpdf.kernel.pdf.PdfWriter.<init>(PdfWriter.java:143)
04-06 23:00:18.514 29260 29260 W System.err: 	at com.itextpdf.kernel.pdf.PdfWriter.<init>(PdfWriter.java:132)
04-06 23:00:18.514 29260 29260 W System.err: 	at com.itextpdf.kernel.pdf.PdfWriter.<init>(PdfWriter.java:105)
04-06 23:00:18.514 29260 29260 W System.err: 	at com.adrienpoupa.attestationcoronavirus.CreateAttestationActivity.generate(CreateAttestationActivity.java:150)
04-06 23:00:18.514 29260 29260 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-06 23:00:18.514 29260 29260 W System.err: 	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:397)
04-06 23:00:18.514 29260 29260 W System.err: 	at android.view.View.performClick(View.java:7259)
04-06 23:00:18.514 29260 29260 W System.err: 	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:967)
04-06 23:00:18.514 29260 29260 W System.err: 	at android.view.View.performClickInternal(View.java:7236)
04-06 23:00:18.514 29260 29260 W System.err: 	at android.view.View.access$3600(View.java:801)
04-06 23:00:18.514 29260 29260 W System.err: 	at android.view.View$PerformClick.run(View.java:27892)
04-06 23:00:18.514 29260 29260 W System.err: 	at android.os.Handler.handleCallback(Handler.java:883)
04-06 23:00:18.514 29260 29260 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-06 23:00:18.514 29260 29260 W System.err: 	at android.os.Looper.loop(Looper.java:214)
04-06 23:00:18.514 29260 29260 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
04-06 23:00:18.514 29260 29260 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-06 23:00:18.514 29260 29260 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
04-06 23:00:18.514 29260 29260 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
04-06 23:00:18.515 29260 29260 W System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
04-06 23:00:18.515 29260 29260 W System.err: 	at libcore.io.Linux.open(Native Method)
04-06 23:00:18.515 29260 29260 W System.err: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
04-06 23:00:18.515 29260 29260 W System.err: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
04-06 23:00:18.515 29260 29260 W System.err: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
04-06 23:00:18.515 29260 29260 W System.err: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
04-06 23:00:18.515 29260 29260 W System.err: 	at libcore.io.IoBridge.open(IoBridge.java:482)
04-06 23:00:18.515 29260 29260 W System.err: 	... 21 more
04-06 23:00:20.553  1010 10362 W NotificationService: Toast already killed. pkg=com.adrienpoupa.attestationcoronavirus callback=android.app.ITransientNotification$Stub$Proxy@94d8c30
```
J'ai effacé et créé les répertoires avec le navigateur par défault et j'ai toujours: `EACCES (Permission denied)`

**Comment by AdrienPoupa** [comment]
Salut,

C'est bizarre, as tu accepté la demande de droits de lecture au premier lancement de l'application?

**Comment by stuart12** [comment]
je viens de vérifier les "App permissions" et je vois "Storage" sous "allowed". Sous "denied" il y a "No permissions denied". Donc oui. As-tu pu tester l'app avec Android 10?

**Comment by AdrienPoupa** [comment]
Non, je tourne sous 9. Je vais essayer avec un émulateur

**Comment by AdrienPoupa** [comment]
J'imagine que le problème vient de là https://medium.com/@sriramaripirala/android-10-open-failed-eacces-permission-denied-da8b630a89df
